# Generated by Django 4.2.1 on 2023-06-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_category',
            new_name='product_category',
        ),
    ]
