# Generated by Django 4.2.1 on 2023-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_category_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
