# Generated by Django 4.2.1 on 2023-05-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FAQs',
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
