# Generated by Django 4.2.1 on 2023-06-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About_U'},
        ),
    ]
