# Generated by Django 4.1.3 on 2023-06-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_contactus_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About_Us', 'verbose_name_plural': 'About_Us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact_Us', 'verbose_name_plural': 'Contact_Us'},
        ),
    ]
